### ISSUE TITLE
How can I get the full code of paper "Constraint Preserving Mixers for the Quantum Approximate Optimization Algorithm"

### ISSUE THREAD

**Issue by liangzi802** [OpenQuantumComputing/OpenQuantumComputing#4]
Hello I am reading the document "Constraint Preserving Mixers for the Quantum Approximate Optimization Algorithm" recently, and I am very interested in how to build MIXER in the article. I would like to ask where is the code of the example in the article, because I found it according to the hints in the article and found no relevant code.

**Comment by fgfuchs** [comment]
Hi, did you have a look here?
https://github.com/OpenQuantumComputing/OpenQuantumComputing/blob/main/openquantumcomputing/mixer_utilities.py

**Comment by liangzi802** [comment]
Well, yes, but this program seems to be missing a module called binsymbols, is it not uploaded?

**Comment by fgfuchs** [comment]
Please check out this https://github.com/OpenQuantumComputing/LogicalXMixer and this https://arxiv.org/abs/2306.17083
